### ISSUE TITLE
An error occurs while running Ansible Playbook (redmine: change_admin_passwd)

### ISSUE THREAD

**Issue by y503unavailable** [y503unavailable/redmine-centos-ansible#38]
現象

Ansible Playbook実行中、下記エラーが発生する。
redmine:change_admin_passwd
/bin/sh/bundle コマンドが見つかりません。
https://pbs.twimg.com/media/ED0L42NUcAASAxf?format=jpg&name=medium

発生環境

AWS EC2 t2.medium
イメージ: CentOS 7 (x86_64) - with Updates HVM
/dev/sda1: 10GB

https://twitter.com/ma2muratomonori/status/1170104565326237696

使用スクリプト(2019/9/7 7時）

y503unavailable/redmine-centos-ansible
feature-category-trunk20190629/

**Comment by y503unavailable** [comment]
状況調査

本スクリプトは9/7夜に修正したが、conoha CentOS7.6 1GBで昨晩動作確認している。
AWS Lightsailでも1年前に動作確認している。

発生個所の調査
https://github.com/y503unavailable/redmine-centos-ansible/blob/feature-category-trunk20190629/roles/redmine/tasks/main.yml

直前にansible-commandでbundle呼び出している箇所(データベースのマイグレーション)は正常に処理されている。
change admin passwdでは、リダイレクションを使用している都合で、shellを利用している。
command と同様に、/usr/local/binのパス指定でbundleを実行する。

```
- name: データベースのマイグレーション
  become: yes
  command:
    bundle exec rake db:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
```

変更前

```
- name: change admin passwd
  become: yes
  shell:   RAILS_ENV=production bundle exec rails console  < /tmp/redmine_admin_passchg.rb
  args:
    chdir: "{{ redmine_dir }}"
```

..と考えたが、リダイレクションを使っている都合上、commandではなくshellを使用しているのだった。

commandを使用している箇所も、/usr/local/bin/bundle と決め打ちしているので、
単純に /usr/local/bin/bundle をパス指定することで対応した。
